# Generated by Django 4.0.1 on 2022-01-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='static',
            name='file',
            field=models.FileField(upload_to='static', verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='static',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nazwa pliku'),
        ),
    ]
